package RNG.rng;


/**
 * @author Montahaee
 * @version 1.0
 * @created 08-Oct-2022 5:38:29 PM
 */
public interface RandomSequence<T extends Number> {

	/**
	 * 
	 * @param x is a real number.
	 * @return cumulative distribution function.
	 */
	double cdf(double x);

	/**
	 * 
	 * @return excepted value for random numbers.
	 */
	double exv();

	/**
	 * 
	 * @return probability density function.
	 */
	double mean();

	/**
	 * 
	 * @return probability mass function associated with discrete random variables generated by LCG.
	 */
	double probability();

	/**
	 * A sequence can be thought of as a list of elements with a particular order.
	 * @return sequential integer random number.
	 */
	boolean randomVariable();



	/**
	 * @return the range of the cdf() function.
	 */
	Interval range();


	/**
	 *
	 * @return all needed parameters to build a random generator.
	 */
	T[] getParams();

	/**
	 * 
//	 * @param random_numbers are generated by LCG.
	 * @return true/false according to result of{@link #<RNG.validator.Validation>}.
	 */
	boolean validated();

	/**
	 * 
	 * @return variance for a uniform distribution with [min, max]
	 */
	double var();


}